name: Build & Push User Service

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-push:
    runs-on: ubuntu-latest
    env:
      REGISTRY: ${{ secrets.DOCKER_USERNAME }}
      IMAGE_NAME: user-service
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract Git metadata
        id: vars
        run: |
          echo "sha_short=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

      - name: Build Docker image
        run: docker build -t $REGISTRY/$IMAGE_NAME:${{ steps.vars.outputs.sha_short }} .

      - name: Push Docker image
        run: docker push $REGISTRY/$IMAGE_NAME:${{ steps.vars.outputs.sha_short }}
