name: CI - User Service

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & Push Docker Image
        run: |
          IMAGE=minnuantony/user-service
          SHA_TAG=$IMAGE:sha-${GITHUB_SHA}
          LATEST_TAG=$IMAGE:latest
          docker build -t $SHA_TAG -t $LATEST_TAG .
          docker push $SHA_TAG
          docker push $LATEST_TAG

      - name: Patch Infra Repo with New Image
        uses: actions/checkout@v3
        with:
          repository: exp-tracker-org/infra
          token: ${{ secrets.ORG_GH_TOKEN }}
          path: infra

      - name: Update Deployment Image
        run: |
          cd infra
          sed -i "s|minnuantony/user-service:.*|minnuantony/user-service:sha-${GITHUB_SHA}|" ./user-service/k8s/deployment.yaml
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add ./user-service/k8s/deployment.yaml
          git commit -m "Update user-service image to sha-${GITHUB_SHA}"
          git push
