name: Passive DAST Scan

on:
  workflow_dispatch:

jobs:
  passive-dast:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install OWASP ZAP Baseline
        run: |
          pip install python-owasp-zap-v2.4

      - name: Run Passive Scan
        run: |
          python -m zapv2_baseline -t http://54.86.64.217:32395 -m 1
